name: Livecheck

on:
  workflow_dispatch:
  repository_dispatch:
    types:
    - livecheck
  schedule:
  - cron: '6 8 * * *'

concurrency: livecheck

jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
    - name: Dump GitHub context
      env:
        GITHUB_CONTEXT: ${{ toJSON(github) }}
      run: echo "$GITHUB_CONTEXT"
    - name: Dump job context
      env:
        JOB_CONTEXT: ${{ toJSON(job) }}
      run: echo "$JOB_CONTEXT"
    - name: Dump steps context
      env:
        STEPS_CONTEXT: ${{ toJSON(steps) }}
      run: echo "$STEPS_CONTEXT"
    - name: Dump runner context
      env:
        RUNNER_CONTEXT: ${{ toJSON(runner) }}
      run: echo "$RUNNER_CONTEXT"
    - name: Dump strategy context
      env:
        STRATEGY_CONTEXT: ${{ toJSON(strategy) }}
      run: echo "$STRATEGY_CONTEXT"
    - name: Dump matrix context
      env:
        MATRIX_CONTEXT: ${{ toJSON(matrix) }}
      run: echo "$MATRIX_CONTEXT"
    - name: Dump environment variables
      run: set
  livecheck:
    name: Livecheck
    runs-on: macos-latest
    env:
      HOMEBREW_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3.3.0
    - name: Set up Homebrew
      uses: Homebrew/actions/setup-homebrew@master
    - name: Livecheck
      run: |
        sh update-tap.sh
        git diff
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v4.2.4
      with:
        commit-message: "update tap"
        branch: "livecheck/patch"
        title: "chore: automated changes by livecheck"
        body: "Automated changes by livecheck"
