name: Livecheck

on:
  workflow_dispatch:
  repository_dispatch:
    types:
    - livecheck
  schedule:
  - cron: '6 8 * * *'
permissions: {}

concurrency: livecheck

jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
    - name: Dump GitHub context
      env:
        GITHUB_CONTEXT: ${{ toJSON(github) }}
      run: echo "$GITHUB_CONTEXT"
    - name: Dump job context
      env:
        JOB_CONTEXT: ${{ toJSON(job) }}
      run: echo "$JOB_CONTEXT"
    - name: Dump steps context
      env:
        STEPS_CONTEXT: ${{ toJSON(steps) }}
      run: echo "$STEPS_CONTEXT"
    - name: Dump runner context
      env:
        RUNNER_CONTEXT: ${{ toJSON(runner) }}
      run: echo "$RUNNER_CONTEXT"
    - name: Dump strategy context
      env:
        STRATEGY_CONTEXT: ${{ toJSON(strategy) }}
      run: echo "$STRATEGY_CONTEXT"
    - name: Dump matrix context
      env:
        MATRIX_CONTEXT: ${{ toJSON(matrix) }}
      run: echo "$MATRIX_CONTEXT"
    - name: Dump environment variables
      run: set
  livecheck:
    name: Livecheck
    runs-on: macos-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
    - name: Set up Homebrew
      id: set-up-homebrew
      uses: Homebrew/actions/setup-homebrew@master
    - name: Cache Homebrew Bundler RubyGems
      id: cache
      uses: actions/cache@v4.2.4
      with:
        path: ${{ steps.set-up-homebrew.outputs.gems-path }}
        key: ${{ runner.os }}-rubygems-${{ steps.set-up-homebrew.outputs.gems-hash }}
        restore-keys: ${{ runner.os }}-rubygems-
    - name: Install Homebrew Bundler RubyGems
      if: steps.cache.outputs.cache-hit != 'true'
      run: brew install-bundler-gems
    - name: Set up git config
      # NOTE: The commit email address should be the canonical no-reply email address
      # used by the `github-actions[bot]` bot user.
      # https://api.github.com/users/github-actions%5Bbot%5D
      # https://github.community/t/github-actions-bot-email-address/17204/6
      run: |
        git config user.name github-actions[bot]
        git config user.email 41898282+github-actions[bot]@users.noreply.github.com
    - name: Bump packages
      env:
        # NOTE: `GITHUB_TOKEN` is intentionally used even though created PRs does
        # not trigger GitHub Action workflows and requires manual rebase. Given
        # that updates are infrequent, the cost of manual rebase is lesser than
        # rotating tokens.
        HOMEBREW_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      # NOTE: The `brew bump` command is used instead of `brew bump-formula-pr`
      # and `brew bump-cask-pr` because it handles fetching the latest version
      # and operates on all formulae/casks within a tap.
      run: |
        brew bump --open-pr --no-fork --tap ArloL/tap
