name: brew pr-pull
on:
  pull_request_target:
    types:
    - labeled
permissions: {}
jobs:
  pr-pull:
    if: contains(github.event.pull_request.labels.*.name, 'pr-pull')
    runs-on: ubuntu-22.04
    permissions:
      actions: read
      checks: read
      contents: write
      issues: read
      pull-requests: write
    steps:
    - name: Set up Homebrew
      uses: Homebrew/actions/setup-homebrew@main
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
    - name: Set up git
      uses: Homebrew/actions/git-user-config@main
    - name: Debug pre-pull git state
      env:
        BRANCH: ${{ github.event.pull_request.head.ref }}
      run: |
        set -o xtrace
        git status
        git log --oneline -10
        git branch -av
        git remote -v
        echo "--- remote branch tip ---"
        git ls-remote origin "refs/heads/$BRANCH"
        echo "--- PR head SHA from event ---"
        echo "${{ github.event.pull_request.head.sha }}"
    - name: Pull bottles
      env:
        HOMEBREW_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        PULL_REQUEST: ${{ github.event.pull_request.number }}
      run: |
        set -o xtrace
        brew pr-pull \
          --debug \
          --verbose \
          --workflows tests.yaml \
          --tap="$GITHUB_REPOSITORY" \
          "$PULL_REQUEST"
    - name: Debug post-pull git state
      env:
        BRANCH: ${{ github.event.pull_request.head.ref }}
      run: |
        set -o xtrace
        git status
        git log --oneline -10
        git branch -av
        echo "--- remote branch tip ---"
        git ls-remote origin "refs/heads/$BRANCH"
        echo "--- diff of HEAD vs remote branch ---"
        git fetch origin "$BRANCH"
        git log --oneline HEAD..FETCH_HEAD
        git log --oneline FETCH_HEAD..HEAD
    - name: Push commits
      env:
        BRANCH: ${{ github.event.pull_request.head.ref }}
      run: git push origin "HEAD:$BRANCH"
    - name: Enable auto-merge
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        PULL_REQUEST: ${{ github.event.pull_request.number }}
      run: gh pr merge --auto --merge "$PULL_REQUEST"
